theme: jekyll-theme-cayman
title: Accessibility Toolbar Plugin
description: Simple accessibility toolbox for use in websites
show_downloads: true
github:
  zip_url: https://raw.githubusercontent.com/mickidum/acc_toolbar/master/acctoolbar/acctoolbar.min.js